import type { Metadata } from "next";
import { Open_Sans, Prata } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

export const metadata: Metadata = {
  title: "Wow Borneo",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-openSans",
  weight: ["800", "300", "400", "500", "700"],
});

const prata = Prata({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prata",
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${openSans.variable} ${prata.variable} antialiased font-body`}
        >
          <Providers>{children}</Providers>
          <Toaster />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
