import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

export const metadata: Metadata = {
  title: "Wow Borneo",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${roboto.variable} antialiased font-body bg-[#FAEEE6]`}
        >
          <Providers>{children}</Providers>
          <Toaster />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
